site_name: Treehouse
docs_dir: src
site_dir: site

nav:
  - Home: index.md
  - Solar: solar.md
  - Walls & Insulation: walls.md
  - Gardens: gardens.md

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green

markdown_extensions:
  - tables
  - admonition

plugins:
  - search
  - tags
